### ISSUE TITLE
crash in RequestEndpoints

### ISSUE THREAD

**Issue by bradfitz** [stampzilla/gozwave#10]
This crash happens reliably for me after 5-30 seconds:

```
ERRO[0003] creating config fileopen : no such file or directory 
INFO[0003] Save config:                                 
INFO[0003] Sending: 0104004106bc                        
INFO[0003] Recived: 06                                  
INFO[0003] Recived: 01090141d39c0004100100              
INFO[0003] RESP: &serialapi.Message{Length:0x9, MessageType:0x1, Function:0x41, NodeId:0x0, Data:(*functions.FuncGetNodeProtocolInfo)(0x10b5cdc0)} 
ERRO[0003] creating config fileopen : no such file or directory 
INFO[0003] Save config:                                 
INFO[0003] Sending: 01080013020272040092                
INFO[0003] Recived: 06                                  
WARN[0003] Dropping message function='SendData' with data 0100 (not implemented) 
INFO[0003] Recived: 010401130100                        
INFO[0003] !DeliverUpdate: *commands.CmdManufacturerSpecific 
INFO[0003] Recived: 010e00040002087205014f4457303400    
ERRO[0003] creating config fileopen : no such file or directory 
INFO[0003] Save config:                                 
ERRO[0003] Request endpoint 2:20 - Basic                
ERRO[0003] Request endpoint 2:86 - Version              
ERRO[0003] Request endpoint 2:26 - SwitchMultilevel     
ERRO[0003] Request endpoint 2:27 - SwitchAll            
ERRO[0003] Request endpoint 2:2b - SceneActivation      
ERRO[0003] Request endpoint 2:2c - SceneActuatorConf    
ERRO[0003] Request endpoint 2:70 - Configuration        
ERRO[0003] Request endpoint 2:72 - ManufacturerSpecific 
ERRO[0003] Request endpoint 2:73 - PowerLevel           


ERRO[0003] Request endpoint 2                           
INFO[0003] Sending: 01080013040272040094                
INFO[0003] Recived: 06                                  
WARN[0003] Dropping message function='SendData' with data 0100 (not implemented) 
INFO[0003] Recived: 010401130100                        
INFO[0003] !DeliverUpdate: *commands.CmdManufacturerSpecific 
INFO[0003] Recived: 010e0004000408720500634952303200    
ERRO[0003] creating config fileopen : no such file or directory 
INFO[0003] Save config:                                 
WARN[0003] Ended identification on node 4               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x45da0c]

goroutine 12 [running]:
github.com/stampzilla/gozwave/nodes.(*Node).RequestEndpoints(0x10b341c0, 0x10ac6d00, 0x0)
        /home/bradfitz/src/github.com/stampzilla/gozwave/nodes/request_endpoints.go:15 +0x1c
github.com/stampzilla/gozwave/nodes.(*Node).Identify(0x10b341c0)
        /home/bradfitz/src/github.com/stampzilla/gozwave/nodes/node.go:217 +0x358
created by github.com/stampzilla/gozwave/nodes.(*Node).Worker
        /home/bradfitz/src/github.com/stampzilla/gozwave/nodes/node.go:136 +0x78
```

On this last line here:

```go
func (n *Node) RequestEndpoints() error {
        // Todo: Send raw messages here                                                                                                                                 

        if n.Device.CommandClasses == nil {
```

So it looks like `n.Device` is nil.

**Comment by stamp** [comment]
The root cause for that is probably that your device 0063-4952-3032 (node 4) is not found in the device database and thats why the n.Device is never set.

A quick fix is just to add a check if n.Device == nil and then return an error

But the real fix would be to use the device classification data (generic class and specific class) to create a list of mandatory command classes. This is specified in the Sigma Designs document SDS10242-17 Z-Wave Device Class Specification.pdf
